package com.systemdesign.trading.engine;

import com.systemdesign.trading.model.*;
import com.systemdesign.trading.strategy.order.OrderExecutionStrategy;

import java.util.*;

/**
 * MatchingEngine is THE CORE CLASS of the trading system.
 *
 * It maintains one OrderBook per symbol and routes incoming orders to the correct book.
 * The actual matching logic is delegated to OrderExecutionStrategy implementations
 * (MarketOrderStrategy, LimitOrderStrategy) to keep this class focused on orchestration.
 *
 * WHY single-threaded per symbol:
 * - Matching MUST be deterministic: same orders in same sequence → same trades.
 * - Multi-threaded matching within one symbol would require complex locking and
 *   could produce non-deterministic results (race between two matching orders).
 * - DIFFERENT symbols CAN run in parallel (separate order books, no shared state).
 * - Real exchanges (NSE, NYSE) also process each symbol's book sequentially.
 *
 * MATCHING ALGORITHM (price-time priority):
 * 1. For a BUY order: match against ASK side (sellers).
 *    - Market buy: match against best ask regardless of price (sweep the book).
 *    - Limit buy at $105: match against asks with price <= $105.
 * 2. For a SELL order: match against BID side (buyers).
 *    - Market sell: match against best bid regardless of price.
 *    - Limit sell at $95: match against bids with price >= $95.
 * 3. At each price level, orders are matched FIFO (first-come-first-served).
 * 4. If incoming order not fully filled → remaining goes into the order book (for limit orders).
 *    Market orders that can't fill completely are typically cancelled (no resting market orders).
 *
 * CALL CHAIN:
 * TradingService.placeOrder() → MatchingService.submitOrder() → MatchingEngine.submitOrder() →
 * selects strategy based on OrderType → strategy.execute() produces List<Trade> →
 * returned to TradingService for settlement, position updates, notifications
 */
public class MatchingEngine {

    // One order book per symbol: RELIANCE has its own book, TCS has its own, etc.
    private final Map<String, OrderBook> orderBooks = new HashMap<>();

    // Strategy map: OrderType → how to execute it
    private final Map<OrderType, OrderExecutionStrategy> strategies = new HashMap<>();

    public MatchingEngine() {
        // Strategies are registered by AppConfig after construction
    }

    /**
     * Register an execution strategy for an order type.
     * Called by AppConfig during system initialization.
     */
    public void registerStrategy(OrderType type, OrderExecutionStrategy strategy) {
        strategies.put(type, strategy);
    }

    /**
     * Get or create the order book for a symbol.
     * WHY lazy creation: we don't know all symbols upfront (IPOs, new listings).
     */
    public OrderBook getOrCreateOrderBook(String symbol) {
        return orderBooks.computeIfAbsent(symbol, OrderBook::new);
    }

    // =====================================================================
    // CORE: Submit an order for matching
    // =====================================================================

    /**
     * Submit an order to the matching engine.
     *
     * ALGORITHM:
     * 1. Get/create the order book for this symbol.
     * 2. Look up the execution strategy based on order type.
     * 3. Delegate to strategy.execute() which:
     *    a. Checks opposite side of book for matchable orders.
     *    b. Creates trades for each match.
     *    c. Updates both orders (buyer and seller).
     *    d. If order not fully filled, adds remainder to book (limit only).
     * 4. Return all trades generated.
     *
     * @param order The order to match (must be in OPEN status)
     * @return List of trades generated by this order (may be empty if no match)
     */
    public List<Trade> submitOrder(Order order) {
        OrderBook book = getOrCreateOrderBook(order.getSymbol());

        // Look up strategy based on order type
        OrderExecutionStrategy strategy = strategies.get(order.getType());
        if (strategy == null) {
            // Fallback: for STOP_LOSS/STOP_LIMIT that have been triggered,
            // they become MARKET or LIMIT orders. Handle them with the appropriate strategy.
            if (order.getType() == OrderType.STOP_LOSS) {
                strategy = strategies.get(OrderType.MARKET);
            } else if (order.getType() == OrderType.STOP_LIMIT) {
                strategy = strategies.get(OrderType.LIMIT);
            }
        }

        if (strategy == null) {
            throw new IllegalStateException("No strategy registered for order type: " + order.getType());
        }

        // Delegate matching to the strategy
        // The strategy reads from and modifies the order book
        return strategy.execute(order, book);
    }

    // =====================================================================
    // CANCEL: Remove an order from the book
    // =====================================================================

    /**
     * Cancel an order by removing it from the order book.
     *
     * WHY cancellation is important:
     * - Users change their mind (price moved, strategy changed).
     * - Risk management may cancel orders (margin call, circuit breaker triggered).
     * - End of day: all unmatched orders may be auto-cancelled.
     *
     * @return true if the order was found and removed, false otherwise
     */
    public boolean cancelOrder(String orderId, String symbol) {
        OrderBook book = orderBooks.get(symbol);
        if (book == null) return false;
        return book.removeOrder(orderId);
    }

    /**
     * Get the order book for a symbol (read-only access for display).
     */
    public OrderBook getOrderBook(String symbol) {
        return orderBooks.get(symbol);
    }

    /**
     * Get all tracked symbols.
     */
    public Set<String> getTrackedSymbols() {
        return orderBooks.keySet();
    }
}
