package com.systemdesign.gateway.model;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * Simulated HTTP response returned from upstream services or generated by the gateway.
 *
 * Flow: Upstream service → HttpResponse → filter chain (post-processing) → Client
 */
public class HttpResponse {

    private final int statusCode;               // HTTP status code
    private final Map<String, String> headers;  // response headers
    private final String body;                  // response body
    private final long latencyMs;               // round-trip latency in milliseconds
    private final String serviceName;           // which upstream service produced the response

    // ── private constructor wired from Builder ──
    private HttpResponse(Builder builder) {
        this.statusCode = builder.statusCode;
        this.headers = Collections.unmodifiableMap(new HashMap<>(builder.headers));
        this.body = builder.body;
        this.latencyMs = builder.latencyMs;
        this.serviceName = builder.serviceName;
    }

    // ── Getters ──

    public int getStatusCode() { return statusCode; }
    public Map<String, String> getHeaders() { return headers; }
    public String getBody() { return body; }
    public long getLatencyMs() { return latencyMs; }
    public String getServiceName() { return serviceName; }

    public boolean isSuccess() { return statusCode >= 200 && statusCode < 300; }
    public boolean isError() { return statusCode >= 400; }

    @Override
    public String toString() {
        return "HttpResponse{statusCode=%d, serviceName='%s', latencyMs=%d}".formatted(
                statusCode, serviceName, latencyMs);
    }

    // ── Static factories for common responses ──

    /** 200 OK with a body. */
    public static HttpResponse ok(String body) {
        return new Builder(200).body(body).build();
    }

    /** Error response with status code and error message as body. */
    public static HttpResponse error(int status, String message) {
        return new Builder(status)
                .body("{\"error\":\"%s\"}".formatted(message))
                .header("Content-Type", "application/json")
                .build();
    }

    /** 302 redirect to the given location. */
    public static HttpResponse redirect(String location) {
        return new Builder(302)
                .header("Location", location)
                .build();
    }

    // ── Builder ──

    public static class Builder {
        private final int statusCode;
        private Map<String, String> headers = new HashMap<>();
        private String body;
        private long latencyMs;
        private String serviceName;

        /** Primary constructor — status code is required. */
        public Builder(int statusCode) {
            this.statusCode = statusCode;
        }

        public Builder header(String key, String value) { this.headers.put(key, value); return this; }
        public Builder headers(Map<String, String> headers) { this.headers.putAll(headers); return this; }
        public Builder body(String body) { this.body = body; return this; }
        public Builder latencyMs(long latencyMs) { this.latencyMs = latencyMs; return this; }
        public Builder serviceName(String serviceName) { this.serviceName = serviceName; return this; }

        public HttpResponse build() {
            return new HttpResponse(this);
        }
    }
}
